In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', -1)
import sqlite3
conn = sqlite3.connect('example.db')
def select(sql):
    return pd.read_sql(sql,conn)

## Содержание <a id="step5"></a>

Задание 1: [Вывести количество действующих предложений на каждый день 2018 года.](#step1)

Задание 2: [Выбрать из всех работающих на дату 1.09.2018 дебетовых карт клиента ту, которая была выдана последней.](#step2)

Задание 3: [Вывести количество активных клиентов на каждый месяц; долю клиентов, которые «оттекли» в каждом месяце.](#step3)

Задание 4: [Вывести 1000 клиентов, которые первыми набрали 1000 бонусных баллов за покупки в категории «Авиабилеты» и «Отели».](#step4)

## Задание 1: вывести количество действующих предложений на каждый день 2018 года.<a id="step1"></a>

### Для выполнения задания я создал импровизированную таблицу в excel, куда подставил случайные значения id и даты начала и окончания оффера (можно посмотреть ее [здесь](https://yadi.sk/d/FDZBAxu8xHVwPA)) согласно примеру из тестового задания.Сейчас мы ее подгрузим, переведем в sql и выполним запрос

In [2]:
offer = pd.read_excel('offer.xlsx')
offer.head()

   OFFER_ID OFFER_START_DATE OFFER_EXPIRATION_DATE
0  121950   2018-01-28       2018-08-19
1  147111   2017-03-25       2018-05-12
2  147928   2017-09-20       2018-08-31
3  154306   2017-04-03       2018-09-23
4  152166   2017-03-29       2018-10-15

In [3]:
offer.to_sql('offer',
             conn,
             if_exists='replace', 
             index = False)

In [4]:
sql = '''select* 
    from offer 
    limit 5 '''
select(sql)

   OFFER_ID     OFFER_START_DATE OFFER_EXPIRATION_DATE
0  121950    2018-01-28 00:00:00  2018-08-19 00:00:00
1  147111    2017-03-25 00:00:00  2018-05-12 00:00:00
2  147928    2017-09-20 00:00:00  2018-08-31 00:00:00
3  154306    2017-04-03 00:00:00  2018-09-23 00:00:00
4  152166    2017-03-29 00:00:00  2018-10-15 00:00:00

### Таблица подгружена

### Описание данных: 
Таблица OFFERS содержит информацию о кредитных предложениях
клиентов банка. У каждого предложения есть идентификатор (offer_id), дата начала действия
(offer_start_date), дата окончания действия (offer_expiration_date). Предложение считается
действующим на дату dt, если dt находится между offer_start_date и offer_expiration_date для данного
предложения.
#### Задание: вывести количество действующих предложений на каждый день 2018 года.

In [5]:
sql = ''' 
              SELECT DATE(OFFER_START_DATE) as DATE,
                     offer_id,
                     COUNT (offer_id) AS VALLID_OFFER
              FROM offer
              WHERE OFFER_START_DATE BETWEEN '2017-01-01 00:00:00' AND '2018-12-30 00:00:00'
              AND OFFER_EXPIRATION_DATE <= '2018-12-30 00:00:00' 
              GROUP BY DATE(OFFER_START_DATE)
          
      '''
select(sql)

           DATE  OFFER_ID  VALLID_OFFER
0    2017-02-01  120131    3
1    2017-02-02  150639    3
2    2017-02-04  141028    3
3    2017-02-06  127673    3
4    2017-02-07  123488    1
5    2017-02-08  142419    2
6    2017-02-09  178525    3
7    2017-02-10  137064    2
8    2017-02-11  174673    4
9    2017-02-12  159130    4
10   2017-02-13  158301    2
11   2017-02-15  111025    2
12   2017-02-16  112711    6
13   2017-02-17  154080    3
14   2017-02-18  128025    2
15   2017-02-20  187322    2
16   2017-02-21  102377    4
17   2017-02-22  143636    6
18   2017-02-23  137471    3
19   2017-02-24  148415    2
20   2017-02-25  185333    4
21   2017-02-26  193417    2
22   2017-02-27  128677    3
23   2017-02-28  102845    2
24   2017-03-01  175294    1
25   2017-03-02  104060    3
26   2017-03-03  131422    2
27   2017-03-04  117339    4
28   2017-03-05  100174    1
29   2017-03-06  125330    6
30   2017-03-07  135519    6
31   2017-03-08  193248    3
32   2017-03-09  148971    2
33   2017-03-11  126831    1
34   2017-03-12  193974    5
35   2017-03-13  160595    3
36   2017-03-14  182804    4
37   2017-03-15  183074    2
38   2017-03-16  175844    5
39   2017-03-17  142642    3
40   2017-03-18  195054    1
41   2017-03-20  140788    2
42   2017-03-21  107005    2
43   2017-03-22  193935    1
44   2017-03-23  137394    3
45   2017-03-24  162375    1
46   2017-03-25  147111    2
47   2017-03-26  137501    5
48   2017-03-27  178624    2
49   2017-03-28  199921    2
50   2017-03-29  152166    6
51   2017-03-30  191528    2
52   2017-03-31  171068    1
53   2017-04-01  167068    2
54   2017-04-02  135235    2
55   2017-04-03  154306    4
56   2017-04-04  106615    1
57   2017-04-06  137091    1
58   2017-04-07  127539    3
59   2017-04-08  122582    1
60   2017-04-09  178017    5
61   2017-04-10  194975    1
62   2017-04-11  187293    3
63   2017-04-12  129958    4
64   2017-04-14  112721    2
65   2017-04-15  132495    4
66   2017-04-16  145318    6
67   2017-04-17  102593    1
68   2017-04-18  118633    4
69   2017-04-19  131425    2
70   2017-04-20  130100    1
71   2017-04-21  195461    2
72   2017-04-22  100699    3
73   2017-04-23  162452    3
74   2017-04-24  173866    1
75   2017-04-25  120768    4
76   2017-04-26  108570    4
77   2017-04-27  134484    2
78   2017-04-29  112315    4
79   2017-04-30  145319    1
80   2017-05-01  106544    4
81   2017-05-02  157865    3
82   2017-05-03  140810    4
83   2017-05-04  176022    1
84   2017-05-05  159314    2
85   2017-05-07  185806    5
86   2017-05-08  157857    3
87   2017-05-10  102174    3
88   2017-05-11  116942    5
89   2017-05-12  173749    3
90   2017-05-13  183111    3
91   2017-05-15  147748    2
92   2017-05-16  105114    4
93   2017-05-17  190194    4
94   2017-05-18  159515    4
95   2017-05-19  175904    4
96   2017-05-20  170665    4
97   2017-05-21  195315    8
98   2017-05-22  182384    4
99   2017-05-23  187598    3
100  2017-05-24  161183    6
101  2017-05-25  134646    3
102  2017-05-26  125879    3
103  2017-05-27  104290    4
104  2017-05-28  132228    3
105  2017-05-30  165999    3
106  2017-05-31  111936    4
107  2017-06-01  193706    4
108  2017-06-02  188100    1
109  2017-06-03  197264    3
110  2017-06-04  168558    2
111  2017-06-05  122226    2
112  2017-06-06  160923    4
113  2017-06-07  147585    4
114  2017-06-08  123951    1
115  2017-06-09  152356    3
116  2017-06-12  199565    2
117  2017-06-13  156578    2
118  2017-06-14  154723    3
119  2017-06-15  186019    3
120  2017-06-16  123931    1
121  2017-06-18  154866    8
122  2017-06-19  155482    1
123  2017-06-20  188253    2
124  2017-06-21  146663    5
125  2017-06-22  162058    1
126  2017-06-23  168371    1
127  2017-06-24  187693    4
128  2017-06-25  141271    1
129  2017-06-26  116457    1
130  2017-06-27  170324    4
131  2017-06-28  192949    2
132  2017-06-29  102865    2
133  2017-06-30  166181    4
134  2017-07-01  178321    2
135  2017-07-02  172809    4
136  2017-07-03  119992    5
137  2017-07-04  127458    4
138  2017-07-05  158476    1
139  2017-07-06  141508    2
140  2017-07-07  100794    2
141  2017-07-08  180114    5
142  2017-07-09  120660    1
143  2017-07-10  107265    2
144  2017-07-11  104163    2
145  2017-07-12  130201    4
146  2017-07-13  145167    4
147  2017-07-14  189610    1
148  2017-07-16  194171    1
149  2017-07-17  119600    2
150  2017-07-18  111435    2
151  2017-07-19  143208    1
152  2017-07-20  157118    3
153  2017-07-21  143840    3
154  2017-07-22  167307    1
155  2017-07-23  159870    7
156  2017-07-24  188109    2
157  2017-07-25  106303    4
158  2017-07-26  124332    2
159  2017-07-27  132081    4
160  2017-07-28  125474    2
161  2017-07-29  152893    4
162  2017-07-30  148891    1
163  2017-08-01  168588    5
164  2017-08-02  176106    4
165  2017-08-03  105190    1
166  2017-08-04  187258    8
167  2017-08-05  193284    2
168  2017-08-06  182520    1
169  2017-08-07  103368    1
170  2017-08-08  116215    1
171  2017-08-09  102155    1
172  2017-08-10  166604    4
173  2017-08-11  103800    1
174  2017-08-12  121065    2
175  2017-08-13  100678    4
176  2017-08-14  122146    3
177  2017-08-15  169785    2
178  2017-08-16  119691    3
179  2017-08-18  186726    2
180  2017-08-19  157701    5
181  2017-08-20  122107    2
182  2017-08-21  159244    3
183  2017-08-22  106173    5
184  2017-08-23  199640    4
185  2017-08-24  189028    3
186  2017-08-25  125598    3
187  2017-08-26  194155    3
188  2017-08-27  194183    1
189  2017-08-28  161888    3
190  2017-08-29  174540    4
191  2017-08-30  191211    2
192  2017-08-31  141896    2
193  2017-09-01  160298    2
194  2017-09-02  166704    1
195  2017-09-03  108654    3
196  2017-09-04  106366    2
197  2017-09-05  182916    5
198  2017-09-06  105201    2
199  2017-09-07  117526    4
200  2017-09-08  151228    2
201  2017-09-09  187025    3
202  2017-09-10  174558    1
203  2017-09-11  102572    2
204  2017-09-12  144938    2
205  2017-09-13  149381    2
206  2017-09-15  112990    8
207  2017-09-17  135898    3
208  2017-09-18  169367    2
209  2017-09-19  144523    7
210  2017-09-20  147928    2
211  2017-09-21  197045    3
212  2017-09-22  105694    4
213  2017-09-23  120825    2
214  2017-09-24  120908    4
215  2017-09-25  176681    1
216  2017-09-26  125809    2
217  2017-09-27  129105    2
218  2017-09-28  114196    2
219  2017-09-30  116416    1
220  2017-10-01  103043    4
221  2017-10-02  158789    3
222  2017-10-03  180826    2
223  2017-10-04  145663    2
224  2017-10-05  139985    4
225  2017-10-06  115399    3
226  2017-10-07  110127    3
227  2017-10-08  112335    2
228  2017-10-09  120907    5
229  2017-10-10  167564    5
230  2017-10-11  106380    4
231  2017-10-13  189830    2
232  2017-10-14  128476    2
233  2017-10-15  159378    3
234  2017-10-16  139704    1
235  2017-10-17  164477    2
236  2017-10-18  199472    1
237  2017-10-19  190284    2
238  2017-10-20  141239    2
239  2017-10-21  141699    2
240  2017-10-22  153352    1
241  2017-10-23  133137    4
242  2017-10-24  181590    1
243  2017-10-25  112385    3
244  2017-10-26  101349    6
245  2017-10-27  101384    1
246  2017-10-29  103068    3
247  2017-10-30  175098    2
248  2017-10-31  155302    2
249  2017-11-01  113457    3
250  2017-11-02  140546    3
251  2017-11-03  159761    4
252  2017-11-04  100649    7
253  2017-11-05  156648    4
254  2017-11-06  127902    3
255  2017-11-07  167665    2
256  2017-11-08  153346    4
257  2017-11-09  153019    3
258  2017-11-10  197638    1
259  2017-11-11  143095    2
260  2017-11-12  111127    2
261  2017-11-13  109974    1
262  2017-11-14  161059    2
263  2017-11-15  192855    2
264  2017-11-16  158643    2
265  2017-11-17  170354    2
266  2017-11-18  199440    6
267  2017-11-19  151892    1
268  2017-11-20  118086    2
269  2017-11-21  132662    3
270  2017-11-23  175669    6
271  2017-11-24  150391    5
272  2017-11-25  192897    2
273  2017-11-26  129446    2
274  2017-11-27  118500    2
275  2017-11-28  153312    1
276  2017-11-29  158188    1
277  2017-11-30  153438    2
278  2017-12-01  191969    5
279  2017-12-02  192764    1
280  2017-12-03  144779    3
281  2017-12-04  191192    3
282  2017-12-05  135552    1
283  2017-12-06  189789    4
284  2017-12-07  130924    3
285  2017-12-08  123550    3
286  2017-12-09  158789    3
287  2017-12-10  166724    1
288  2017-12-11  177690    1
289  2017-12-12  100312    2
290  2017-12-13  180882    1
291  2017-12-14  196902    2
292  2017-12-15  171063    1
293  2017-12-16  122807    1
294  2017-12-17  167020    2
295  2017-12-18  160479    3
296  2017-12-19  191466    3
297  2017-12-20  178416    3
298  2017-12-21  134381    5
299  2017-12-22  198731    1
300  2017-12-23  161304    3
301  2017-12-24  183638    3
302  2017-12-25  171501    1
303  2017-12-26  104030    4
304  2017-12-27  119804    1
305  2017-12-28  139585    2
306  2017-12-29  158139    2
307  2017-12-30  143990    2
308  2017-12-31  128518    4
309  2018-01-01  146403    3
310  2018-01-02  158212    1
311  2018-01-03  171567    3
312  2018-01-04  167874    3
313  2018-01-05  135774    2
314  2018-01-06  116080    1
315  2018-01-07  191676    3
316  2018-01-08  184732    3
317  2018-01-09  102185    1
318  2018-01-10  127523    3
319  2018-01-11  114515    8
320  2018-01-12  115444    4
321  2018-01-13  123327    3
322  2018-01-14  186068    4
323  2018-01-15  198119    5
324  2018-01-16  113211    4
325  2018-01-18  103869    2
326  2018-01-19  109703    2
327  2018-01-20  151785    1
328  2018-01-21  172247    3
329  2018-01-23  152461    2
330  2018-01-24  169278    1
331  2018-01-25  130942    2
332  2018-01-26  199528    2
333  2018-01-27  124539    4
334  2018-01-28  121950    7
335  2018-01-29  144726    2
336  2018-01-31  164616    2
337  2018-02-01  173010    2

In [6]:
offer.query('OFFER_ID == "121950"')

   OFFER_ID OFFER_START_DATE OFFER_EXPIRATION_DATE
0  121950   2018-01-28       2018-08-19

In [7]:
offer.query('OFFER_ID == "127673"')

     OFFER_ID OFFER_START_DATE OFFER_EXPIRATION_DATE
265  127673   2017-02-06       2018-08-05

### Внизу решение задачи, но к моему сожалению я так и не разобрался как скалькулировать действующие предложения на интервал 2018 года....(

In [8]:
sql = ''' 
          SELECT DATE_START, 
                 SUM(OFFERS) over (order by DATE_START rows between unbounded preceding and current row) AS COUNT_OFFERS
          FROM
             (SELECT DATE(OFFER_START_DATE) as DATE_START,
                     COUNT(offer_id) as OFFERS
                  
              FROM offer
              WHERE OFFER_START_DATE BETWEEN '2017-01-01 00:00:00' AND '2018-12-31 00:00:00'
                    AND OFFER_EXPIRATION_DATE <= '2018-12-31 00:00:00 ' 
              GROUP BY DATE(OFFER_START_DATE))
            
      '''
select(sql)

     DATE_START  COUNT_OFFERS
0    2017-02-01  3
1    2017-02-02  6
2    2017-02-04  9
3    2017-02-06  12
4    2017-02-07  14
5    2017-02-08  16
6    2017-02-09  19
7    2017-02-10  21
8    2017-02-11  25
9    2017-02-12  29
10   2017-02-13  31
11   2017-02-15  33
12   2017-02-16  39
13   2017-02-17  42
14   2017-02-18  44
15   2017-02-20  46
16   2017-02-21  50
17   2017-02-22  56
18   2017-02-23  59
19   2017-02-24  61
20   2017-02-25  65
21   2017-02-26  67
22   2017-02-27  70
23   2017-02-28  72
24   2017-03-01  73
25   2017-03-02  76
26   2017-03-03  78
27   2017-03-04  82
28   2017-03-05  83
29   2017-03-06  89
30   2017-03-07  95
31   2017-03-08  98
32   2017-03-09  100
33   2017-03-11  101
34   2017-03-12  106
35   2017-03-13  109
36   2017-03-14  113
37   2017-03-15  115
38   2017-03-16  120
39   2017-03-17  123
40   2017-03-18  124
41   2017-03-20  126
42   2017-03-21  128
43   2017-03-22  129
44   2017-03-23  132
45   2017-03-24  133
46   2017-03-25  135
47   2017-03-26  140
48   2017-03-27  142
49   2017-03-28  144
50   2017-03-29  150
51   2017-03-30  152
52   2017-03-31  153
53   2017-04-01  155
54   2017-04-02  157
55   2017-04-03  161
56   2017-04-04  162
57   2017-04-06  163
58   2017-04-07  166
59   2017-04-08  167
60   2017-04-09  172
61   2017-04-10  173
62   2017-04-11  176
63   2017-04-12  180
64   2017-04-14  182
65   2017-04-15  186
66   2017-04-16  192
67   2017-04-17  193
68   2017-04-18  197
69   2017-04-19  199
70   2017-04-20  200
71   2017-04-21  202
72   2017-04-22  205
73   2017-04-23  208
74   2017-04-24  209
75   2017-04-25  213
76   2017-04-26  217
77   2017-04-27  219
78   2017-04-29  223
79   2017-04-30  224
80   2017-05-01  228
81   2017-05-02  231
82   2017-05-03  235
83   2017-05-04  236
84   2017-05-05  238
85   2017-05-07  243
86   2017-05-08  246
87   2017-05-10  249
88   2017-05-11  254
89   2017-05-12  257
90   2017-05-13  260
91   2017-05-15  262
92   2017-05-16  266
93   2017-05-17  270
94   2017-05-18  274
95   2017-05-19  278
96   2017-05-20  282
97   2017-05-21  290
98   2017-05-22  294
99   2017-05-23  297
100  2017-05-24  303
101  2017-05-25  306
102  2017-05-26  309
103  2017-05-27  313
104  2017-05-28  316
105  2017-05-30  319
106  2017-05-31  323
107  2017-06-01  327
108  2017-06-02  328
109  2017-06-03  331
110  2017-06-04  333
111  2017-06-05  335
112  2017-06-06  339
113  2017-06-07  343
114  2017-06-08  344
115  2017-06-09  347
116  2017-06-12  349
117  2017-06-13  351
118  2017-06-14  354
119  2017-06-15  357
120  2017-06-16  358
121  2017-06-18  366
122  2017-06-19  367
123  2017-06-20  369
124  2017-06-21  374
125  2017-06-22  375
126  2017-06-23  376
127  2017-06-24  380
128  2017-06-25  381
129  2017-06-26  382
130  2017-06-27  386
131  2017-06-28  388
132  2017-06-29  390
133  2017-06-30  394
134  2017-07-01  396
135  2017-07-02  400
136  2017-07-03  405
137  2017-07-04  409
138  2017-07-05  410
139  2017-07-06  412
140  2017-07-07  414
141  2017-07-08  419
142  2017-07-09  420
143  2017-07-10  422
144  2017-07-11  424
145  2017-07-12  428
146  2017-07-13  432
147  2017-07-14  433
148  2017-07-16  434
149  2017-07-17  436
150  2017-07-18  438
151  2017-07-19  439
152  2017-07-20  442
153  2017-07-21  445
154  2017-07-22  446
155  2017-07-23  453
156  2017-07-24  455
157  2017-07-25  459
158  2017-07-26  461
159  2017-07-27  465
160  2017-07-28  467
161  2017-07-29  471
162  2017-07-30  472
163  2017-08-01  477
164  2017-08-02  481
165  2017-08-03  482
166  2017-08-04  490
167  2017-08-05  492
168  2017-08-06  493
169  2017-08-07  494
170  2017-08-08  495
171  2017-08-09  496
172  2017-08-10  500
173  2017-08-11  501
174  2017-08-12  503
175  2017-08-13  508
176  2017-08-14  511
177  2017-08-15  513
178  2017-08-16  516
179  2017-08-18  518
180  2017-08-19  523
181  2017-08-20  525
182  2017-08-21  528
183  2017-08-22  533
184  2017-08-23  537
185  2017-08-24  540
186  2017-08-25  543
187  2017-08-26  546
188  2017-08-27  547
189  2017-08-28  550
190  2017-08-29  554
191  2017-08-30  556
192  2017-08-31  558
193  2017-09-01  560
194  2017-09-02  561
195  2017-09-03  564
196  2017-09-04  566
197  2017-09-05  571
198  2017-09-06  573
199  2017-09-07  577
200  2017-09-08  579
201  2017-09-09  582
202  2017-09-10  583
203  2017-09-11  585
204  2017-09-12  587
205  2017-09-13  589
206  2017-09-15  597
207  2017-09-17  600
208  2017-09-18  602
209  2017-09-19  609
210  2017-09-20  611
211  2017-09-21  614
212  2017-09-22  618
213  2017-09-23  620
214  2017-09-24  624
215  2017-09-25  625
216  2017-09-26  627
217  2017-09-27  629
218  2017-09-28  631
219  2017-09-30  632
220  2017-10-01  636
221  2017-10-02  639
222  2017-10-03  641
223  2017-10-04  643
224  2017-10-05  647
225  2017-10-06  650
226  2017-10-07  653
227  2017-10-08  655
228  2017-10-09  660
229  2017-10-10  665
230  2017-10-11  669
231  2017-10-13  671
232  2017-10-14  673
233  2017-10-15  676
234  2017-10-16  677
235  2017-10-17  679
236  2017-10-18  680
237  2017-10-19  682
238  2017-10-20  684
239  2017-10-21  686
240  2017-10-22  687
241  2017-10-23  691
242  2017-10-24  692
243  2017-10-25  695
244  2017-10-26  701
245  2017-10-27  702
246  2017-10-29  705
247  2017-10-30  707
248  2017-10-31  709
249  2017-11-01  712
250  2017-11-02  715
251  2017-11-03  719
252  2017-11-04  726
253  2017-11-05  730
254  2017-11-06  733
255  2017-11-07  735
256  2017-11-08  739
257  2017-11-09  742
258  2017-11-10  743
259  2017-11-11  745
260  2017-11-12  747
261  2017-11-13  748
262  2017-11-14  750
263  2017-11-15  752
264  2017-11-16  754
265  2017-11-17  756
266  2017-11-18  762
267  2017-11-19  763
268  2017-11-20  765
269  2017-11-21  768
270  2017-11-23  774
271  2017-11-24  779
272  2017-11-25  781
273  2017-11-26  783
274  2017-11-27  785
275  2017-11-28  786
276  2017-11-29  787
277  2017-11-30  789
278  2017-12-01  795
279  2017-12-02  796
280  2017-12-03  799
281  2017-12-04  802
282  2017-12-05  803
283  2017-12-06  807
284  2017-12-07  810
285  2017-12-08  813
286  2017-12-09  816
287  2017-12-10  817
288  2017-12-11  818
289  2017-12-12  820
290  2017-12-13  821
291  2017-12-14  823
292  2017-12-15  824
293  2017-12-16  825
294  2017-12-17  827
295  2017-12-18  830
296  2017-12-19  833
297  2017-12-20  836
298  2017-12-21  841
299  2017-12-22  842
300  2017-12-23  845
301  2017-12-24  848
302  2017-12-25  849
303  2017-12-26  853
304  2017-12-27  854
305  2017-12-28  856
306  2017-12-29  858
307  2017-12-30  860
308  2017-12-31  864
309  2018-01-01  867
310  2018-01-02  868
311  2018-01-03  871
312  2018-01-04  874
313  2018-01-05  876
314  2018-01-06  877
315  2018-01-07  880
316  2018-01-08  883
317  2018-01-09  884
318  2018-01-10  887
319  2018-01-11  895
320  2018-01-12  899
321  2018-01-13  902
322  2018-01-14  906
323  2018-01-15  911
324  2018-01-16  915
325  2018-01-18  917
326  2018-01-19  919
327  2018-01-20  920
328  2018-01-21  923
329  2018-01-23  925
330  2018-01-24  926
331  2018-01-25  928
332  2018-01-26  930
333  2018-01-27  934
334  2018-01-28  941
335  2018-01-29  943
336  2018-01-31  945
337  2018-02-01  947

## Задание 2: выбрать из всех работающих на дату 1.09.2018 дебетовых карт клиента ту, которая была выдана последней. Формат выдачи – client_id, card_id.<a id="step2"></a>

### Для выполнения задания я создал импровизированную таблицу в excel, куда подставил случайные значения id, номер карты, даты начала и окончания срока действия карты (можно посмотреть ее [здесь](https://yadi.sk/d/nwnoc1igsO9PVA) )согласно примеру из тестового задания.Сейчас мы ее подгрузим, переведем в sql и выполним запрос

In [9]:
card = pd.read_excel('card.xlsx')
card.head()

   CLIENT_ID           CARD_ID  OPEN_DATE CLOSE_DATE  CARD_TYPE
0  1279427    5536025649810404 2018-07-08 2018-09-05  1
1  1172818    5536053972984040 2017-10-07 2018-02-25  1
2  1052058    5536025796520656 2017-05-10 NaT         1
3  1437607    5536000769000677 2017-05-10 NaT         2
4  1359277    5536064693140589 2017-12-04 NaT         1

In [10]:
card.to_sql('card',
             conn,
             if_exists='replace', 
             index = False)

In [11]:
sql = '''select* 
         from card 
         limit 5 
      '''
select(sql)

,CLIENT_ID,CARD_ID,OPEN_DATE,CLOSE_DATE,CARD_TYPE
0,1279427,5536025649810404,2018-07-08 00:00:00,2018-09-05 00:00:00,1
1,1172818,5536053972984040,2017-10-07 00:00:00,2018-02-25 00:00:00,1
2,1052058,5536025796520656,2017-05-10 00:00:00,None,1
3,1437607,5536000769000677,2017-05-10 00:00:00,None,2
4,1359277,5536064693140589,2017-12-04 00:00:00,None,1

### Описание данных
Таблица CARDS содержит информацию о всех картах клиентов банка. Атрибуты:
идентификатор клиента (client_id), идентификатор карты (card_id), дата выдачи карты (open_date), дата
закрытия карты (close_date), тип карты – дебетовая (1) или кредитная (2) (card_type).
#### Задание: выбрать из всех работающих на дату 1.09.2018 дебетовых карт клиента ту, которая была выдана последней. Формат выдачи – client_id, card_id.

### Здесь у меня получилось 2 решения: 1 простым запросом с фильтрацией, а второе с применением оконной функции. Исходя из условия задачи и тот и другой путь является верным, а если бы в условии задачи ну было нати клиента, который получи  1678982-ю карту, конечно нужно использовать вариант решения 2

### Решение 1

In [12]:
sql = '''SELECT client_id,
                card_id,
                open_date
         FROM CARD
         WHERE OPEN_DATE < '2018-09-01 00:00:00' AND CLOSE_DATE is null AND CARD_TYPE = '1'
         ORDER BY (OPEN_DATE) DESC
    '''
select(sql)

      CLIENT_ID           CARD_ID            OPEN_DATE
0     1683431    5536030318406556  2018-08-31 00:00:00
1     1354160    5536036595118695  2018-08-31 00:00:00
2     1367441    5536037626283780  2018-08-31 00:00:00
3     1398292    5536016637519291  2018-08-31 00:00:00
4     1517424    5536077114157491  2018-08-31 00:00:00
5     1308347    5536096385435992  2018-08-31 00:00:00
6     1856269    5536011276884741  2018-08-31 00:00:00
7     1544955    5536085583528680  2018-08-31 00:00:00
8     1393959    5536013878092339  2018-08-30 00:00:00
9     1787695    5536078513194739  2018-08-30 00:00:00
10    1400169    5536032072094198  2018-08-30 00:00:00
11    1851354    5536048626295924  2018-08-30 00:00:00
12    1544804    5536019392352809  2018-08-30 00:00:00
13    1647834    5536023173626971  2018-08-30 00:00:00
14    1203687    5536041606657335  2018-08-30 00:00:00
15    1280308    5536011007246118  2018-08-30 00:00:00
16    1396291    5536017201414029  2018-08-29 00:00:00
17    1058539    5536081258936802  2018-08-29 00:00:00
18    1641981    5536013498426361  2018-08-29 00:00:00
19    1102493    5536096393909986  2018-08-29 00:00:00
20    1244450    5536068901608218  2018-08-29 00:00:00
21    1254962    5536099804361997  2018-08-29 00:00:00
22    1751670    5536068776082228  2018-08-29 00:00:00
23    1054770    5536025214961292  2018-08-29 00:00:00
24    1142964    5536073018404231  2018-08-29 00:00:00
25    1968876    5536083271131714  2018-08-29 00:00:00
26    1845657    5536035121790757  2018-08-29 00:00:00
27    1442726    5536063638625377  2018-08-29 00:00:00
28    1560610    5536063545585489  2018-08-29 00:00:00
29    1487385    5536045155211712  2018-08-28 00:00:00
30    1881485    5536072206463782  2018-08-28 00:00:00
31    1121534    5536048445730566  2018-08-28 00:00:00
32    1093005    5536034119873155  2018-08-28 00:00:00
33    1200264    5536087719253912  2018-08-28 00:00:00
34    1217053    5536027131942411  2018-08-28 00:00:00
35    1065187    5536002609385027  2018-08-28 00:00:00
36    1173428    5536062769757268  2018-08-28 00:00:00
37    1912907    5536020093069137  2018-08-28 00:00:00
38    1535889    5536044906278043  2018-08-28 00:00:00
39    1741134    5536021539193606  2018-08-28 00:00:00
40    1385794    5536002859984243  2018-08-28 00:00:00
41    1311363    5536087208779144  2018-08-27 00:00:00
42    1921171    5536025421082860  2018-08-27 00:00:00
43    1444713    5536065453535656  2018-08-27 00:00:00
44    1153358    5536005974868100  2018-08-27 00:00:00
45    1919817    5536042626192132  2018-08-27 00:00:00
46    1091568    5536082988968240  2018-08-27 00:00:00
47    1913638    5536057080457704  2018-08-27 00:00:00
48    1355678    5536028046101280  2018-08-26 00:00:00
49    1013463    5536077329894561  2018-08-26 00:00:00
50    1105528    5536096518904017  2018-08-26 00:00:00
51    1709076    5536085926573280  2018-08-26 00:00:00
52    1450169    5536018598815070  2018-08-26 00:00:00
53    1326425    5536080769660283  2018-08-26 00:00:00
54    1689237    5536015665233909  2018-08-25 00:00:00
55    1882591    5536030245247323  2018-08-25 00:00:00
56    1236386    5536027666265012  2018-08-25 00:00:00
57    1096202    5536028646048032  2018-08-25 00:00:00
58    1209972    5536084719149476  2018-08-25 00:00:00
59    1752369    5536033244449304  2018-08-25 00:00:00
60    1774795    5536019151644593  2018-08-24 00:00:00
61    1592527    5536030137759075  2018-08-24 00:00:00
62    1118610    5536047835031221  2018-08-24 00:00:00
63    1286155    5536073776254185  2018-08-24 00:00:00
64    1709409    5536055186668785  2018-08-24 00:00:00
65    1294791    5536027930301227  2018-08-24 00:00:00
66    1954068    5536082962520330  2018-08-23 00:00:00
67    1662286    5536095808344943  2018-08-23 00:00:00
68    1201036    5536006454436224  2018-08-23 00:00:00
69    1697809    5536030761869900  2018-08-23 00:00:00
70    1934362    5536035417802246  2018-08-23 00:00:00
71    1155623    5536043524595503  2018-08-23 00:00:00
72    1050546    5536035073975683  2018-08-23 00:00:00
73    1987609    5536008237221270  2018-08-22 00:00:00
74    1670438    5536040506929593  2018-08-22 00:00:00
75    1257291    5536025880543441  2018-08-22 00:00:00
76    1338098    5536045153852194  2018-08-22 00:00:00
77    1242953    5536077233991813  2018-08-22 00:00:00
78    1706173    5536060479172534  2018-08-22 00:00:00
79    1375814    5536041160451046  2018-08-22 00:00:00
80    1673434    5536068029625623  2018-08-22 00:00:00
81    1785890    5536033584547406  2018-08-22 00:00:00
82    1579278    5536068528639409  2018-08-22 00:00:00
83    1325649    5536056325329814  2018-08-22 00:00:00
84    1528876    5536074456900186  2018-08-21 00:00:00
85    1748118    5536081154786931  2018-08-21 00:00:00
86    1779163    5536077516018536  2018-08-21 00:00:00
87    1118446    5536002803572750  2018-08-21 00:00:00
88    1555750    5536050721955448  2018-08-21 00:00:00
89    1042212    5536076763101399  2018-08-21 00:00:00
90    1799033    5536055800027852  2018-08-21 00:00:00
91    1599439    5536012277077795  2018-08-21 00:00:00
92    1594807    5536063668637401  2018-08-21 00:00:00
93    1169782    5536034003654602  2018-08-20 00:00:00
94    1768531    5536046940256790  2018-08-20 00:00:00
95    1878008    5536062131859603  2018-08-20 00:00:00
96    1688566    5536051446992317  2018-08-20 00:00:00
97    1195713    5536077726328415  2018-08-20 00:00:00
98    1573837    5536006096645074  2018-08-20 00:00:00
99    1658585    5536071307101552  2018-08-20 00:00:00
100   1967091    5536087341263954  2018-08-20 00:00:00
101   1528373    5536076079664139  2018-08-19 00:00:00
102   1282968    5536057103789715  2018-08-19 00:00:00
103   1382797    5536078181772219  2018-08-19 00:00:00
104   1225110    5536063960124943  2018-08-19 00:00:00
105   1934598    5536048556012876  2018-08-19 00:00:00
106   1501941    5536002864134078  2018-08-19 00:00:00
107   1549036    5536044104434247  2018-08-19 00:00:00
108   1854618    5536070092817485  2018-08-19 00:00:00
109   1095014    5536008307723627  2018-08-19 00:00:00
110   1997560    5536016220089016  2018-08-18 00:00:00
111   1074427    5536023384250783  2018-08-18 00:00:00
112   1341213    5536031108637986  2018-08-18 00:00:00
113   1099545    5536042091574033  2018-08-18 00:00:00
114   1617137    5536076864181782  2018-08-18 00:00:00
115   1162908    5536072799116862  2018-08-18 00:00:00
116   1385060    5536046726882277  2018-08-18 00:00:00
117   1149514    5536099945371364  2018-08-18 00:00:00
118   1531897    5536047514835139  2018-08-17 00:00:00
119   1449348    5536064898372323  2018-08-17 00:00:00
120   1601687    5536034516552409  2018-08-17 00:00:00
121   1715854    5536019078012594  2018-08-17 00:00:00
122   1639691    5536084187282430  2018-08-17 00:00:00
123   1618613    5536065184687088  2018-08-17 00:00:00
124   1508148    5536003704761813  2018-08-17 00:00:00
125   1525940    5536055004513713  2018-08-17 00:00:00
126   1839793    5536094674629710  2018-08-17 00:00:00
127   1332479    5536077528190807  2018-08-17 00:00:00
128   1712747    5536038040662407  2018-08-17 00:00:00
129   1583032    5536071769367163  2018-08-16 00:00:00
130   1936615    5536020669192229  2018-08-16 00:00:00
131   1990141    5536015028971638  2018-08-16 00:00:00
132   1645104    5536069494780836  2018-08-16 00:00:00
133   1875845    5536073321163847  2018-08-16 00:00:00
134   1023778    5536044608232358  2018-08-16 00:00:00
135   1763374    5536068418439454  2018-08-16 00:00:00
136   1477009    5536088767914504  2018-08-16 00:00:00
137   1559092    5536023340678902  2018-08-16 00:00:00
138   1669700    5536029030203803  2018-08-15 00:00:00
139   1518348    5536000951100060  2018-08-15 00:00:00
140   1504868    5536037043195744  2018-08-15 00:00:00
141   1328074    5536016499048997  2018-08-15 00:00:00
142   1327445    5536088213781798  2018-08-15 00:00:00
143   1216692    5536053994742434  2018-08-14 00:00:00
144   1513337    5536011872484032  2018-08-14 00:00:00
145   1553961    5536042628930597  2018-08-14 00:00:00
146   1316798    5536047954974500  2018-08-14 00:00:00
147   1808035    5536024265925149  2018-08-14 00:00:00
148   1942886    5536000927456324  2018-08-14 00:00:00
149   1756525    5536032447660910  2018-08-14 00:00:00
150   1440036    5536043964071608  2018-08-14 00:00:00
151   1982737    5536099262864360  2018-08-14 00:00:00
152   1708476    5536071154962426  2018-08-14 00:00:00
153   1351480    5536022993579499  2018-08-14 00:00:00
154   1996391    5536066606035622  2018-08-13 00:00:00
155   1184075    5536068578904546  2018-08-13 00:00:00
156   1012489    5536036777106194  2018-08-13 00:00:00
157   1748341    5536068150424360  2018-08-13 00:00:00
158   1608694    5536073305634007  2018-08-13 00:00:00
159   1013468    5536075740993576  2018-08-13 00:00:00
160   1962500    5536046989406989  2018-08-12 00:00:00
161   1702436    5536086345600555  2018-08-12 00:00:00
162   1690185    5536045307336444  2018-08-12 00:00:00
163   1107110    5536046414822922  2018-08-12 00:00:00
164   1435738    5536087133646975  2018-08-12 00:00:00
165   1874991    5536000745311826  2018-08-12 00:00:00
166   1231312    5536094489873775  2018-08-12 00:00:00
167   1068483    5536037410231432  2018-08-12 00:00:00
168   1511756    5536033375303225  2018-08-11 00:00:00
169   1138658    5536061768680281  2018-08-11 00:00:00
170   1546818    5536067201797918  2018-08-11 00:00:00
171   1409290    5536099946621979  2018-08-11 00:00:00
172   1622396    5536049118448280  2018-08-11 00:00:00
173   1351286    5536043669454467  2018-08-11 00:00:00
174   1563478    5536089370022662  2018-08-11 00:00:00
175   1337022    5536078866641283  2018-08-11 00:00:00
176   1209592    5536002800699957  2018-08-11 00:00:00
177   1537743    5536038756710319  2018-08-11 00:00:00
178   1972014    5536027597192367  2018-08-11 00:00:00
179   1635871    5536013038739084  2018-08-10 00:00:00
180   1077335    5536058823440842  2018-08-10 00:00:00
181   1616187    5536014908586058  2018-08-10 00:00:00
182   1566250    5536088560465459  2018-08-10 00:00:00
183   1635043    5536093909015279  2018-08-10 00:00:00
184   1407751    5536008434803429  2018-08-09 00:00:00
185   1238863    5536097708629489  2018-08-09 00:00:00
186   1045744    5536073018629214  2018-08-08 00:00:00
187   1931923    5536012388560138  2018-08-08 00:00:00
188   1919492    5536039583675552  2018-08-08 00:00:00
189   1812176    5536013181259881  2018-08-08 00:00:00
190   1969453    5536043042429681  2018-08-08 00:00:00
191   1225788    5536043320269014  2018-08-08 00:00:00
192   1715240    5536043572090023  2018-08-07 00:00:00
193   1389268    5536031177483886  2018-08-07 00:00:00
194   1276230    5536008884469163  2018-08-07 00:00:00
195   1454479    5536067405613627  2018-08-07 00:00:00
196   1376828    5536059525367649  2018-08-07 00:00:00
197   1639461    5536020838686414  2018-08-07 00:00:00
198   1122211    5536055284741765  2018-08-07 00:00:00
199   1717477    5536016159606227  2018-08-07 00:00:00
200   1590759    5536090641879340  2018-08-07 00:00:00
201   1580592    5536023719453596  2018-08-06 00:00:00
202   1243725    5536080593150828  2018-08-06 00:00:00
203   1749640    5536030802239062  2018-08-06 00:00:00
204   1237728    5536039776075983  2018-08-06 00:00:00
205   1465577    5536092500258204  2018-08-06 00:00:00
206   1193380    5536076005124747  2018-08-06 00:00:00
207   1419681    5536011655463264  2018-08-05 00:00:00
208   1166289    5536055292411654  2018-08-05 00:00:00
209   1382222    5536059550103208  2018-08-05 00:00:00
210   1762385    5536095289627798  2018-08-05 00:00:00
211   1209367    5536018443218418  2018-08-05 00:00:00
212   1361405    5536060520811654  2018-08-05 00:00:00
213   1611646    5536071165159704  2018-08-05 00:00:00
214   1700593    5536061851961349  2018-08-05 00:00:00
215   1788072    5536058052701852  2018-08-05 00:00:00
216   1932670    5536012989863954  2018-08-04 00:00:00
217   1772605    5536098055650093  2018-08-04 00:00:00
218   1483877    5536078533601698  2018-08-04 00:00:00
219   1157705    5536000637897542  2018-08-04 00:00:00
220   1887822    5536073063723319  2018-08-04 00:00:00
221   1224398    5536083824652343  2018-08-04 00:00:00
222   1355717    5536056073261999  2018-08-04 00:00:00
223   1455853    5536049139078696  2018-08-04 00:00:00
224   1499254    5536071898339434  2018-08-04 00:00:00
225   1613366    5536078953805583  2018-08-04 00:00:00
226   1381022    5536099149999945  2018-08-03 00:00:00
227   1084059    5536059620005720  2018-08-03 00:00:00
228   1128838    5536004540457562  2018-08-03 00:00:00
229   1973301    5536028071220078  2018-08-03 00:00:00
230   1861952    5536061175653395  2018-08-03 00:00:00
231   1566313    5536084751662464  2018-08-03 00:00:00
232   1619939    5536035967529285  2018-08-03 00:00:00
233   1535382    5536022532170154  2018-08-03 00:00:00
234   1403865    5536081629674229  2018-08-03 00:00:00
235   1495282    5536095631399767  2018-08-03 00:00:00
236   1719134    5536089754507350  2018-08-03 00:00:00
237   1070796    5536028251196316  2018-08-03 00:00:00
238   1198433    5536014045629934  2018-08-03 00:00:00
239   1613055    5536051864809588  2018-08-03 00:00:00
240   1978199    5536099962951030  2018-08-03 00:00:00
241   1988572    5536043411241234  2018-08-02 00:00:00
242   1629430    5536020642292009  2018-08-02 00:00:00
243   1870607    5536065481847654  2018-08-02 00:00:00
244   1096732    5536055752736362  2018-08-02 00:00:00
245   1199606    5536011644608642  2018-08-02 00:00:00
246   1882199    5536079624897893  2018-08-02 00:00:00
247   1400333    5536079071190579  2018-08-02 00:00:00
248   1492525    5536069436642429  2018-08-02 00:00:00
249   1178923    5536017849744128  2018-08-02 00:00:00
250   1738784    5536012846364399  2018-08-01 00:00:00
251   1513845    5536027906753489  2018-08-01 00:00:00
252   1272977    5536048937944193  2018-08-01 00:00:00
253   1010731    5536006240998670  2018-08-01 00:00:00
254   1052753    5536027046100283  2018-08-01 00:00:00
255   1982259    5536087019974886  2018-08-01 00:00:00
256   1102469    5536042415420233  2018-08-01 00:00:00
257   1550413    5536003550993518  2018-07-31 00:00:00
258   1639342    5536079662693982  2018-07-31 00:00:00
259   1538132    5536068046289651  2018-07-31 00:00:00
260   1255285    5536012001109160  2018-07-31 00:00:00
261   1793223    5536035339365505  2018-07-30 00:00:00
262   1149515    5536041851090055  2018-07-30 00:00:00
263   1262940    5536019602163568  2018-07-30 00:00:00
264   1199835    5536067472598807  2018-07-30 00:00:00
265   1568017    5536011771528369  2018-07-29 00:00:00
266   1014252    5536083067704900  2018-07-29 00:00:00
267   1974389    5536029428104183  2018-07-29 00:00:00
268   1985833    5536092506479997  2018-07-29 00:00:00
269   1865299    5536048579808649  2018-07-29 00:00:00
270   1356868    5536049741417398  2018-07-29 00:00:00
271   1723008    5536081229174986  2018-07-29 00:00:00
272   1757885    5536074196769125  2018-07-29 00:00:00
273   1793383    5536006568472658  2018-07-29 00:00:00
274   1694642    5536009978236187  2018-07-29 00:00:00
275   1723102    5536077560020308  2018-07-29 00:00:00
276   1301129    5536034925382395  2018-07-29 00:00:00
277   1180244    5536038637899214  2018-07-28 00:00:00
278   1782238    5536054601170484  2018-07-28 00:00:00
279   1719934    5536088414712944  2018-07-28 00:00:00
280   1326459    5536045440577996  2018-07-28 00:00:00
281   1354791    5536015886949299  2018-07-28 00:00:00
282   1905844    5536029684561280  2018-07-28 00:00:00
283   1959990    5536069626533702  2018-07-28 00:00:00
284   1452473    5536057821771059  2018-07-28 00:00:00
285   1442019    5536059515679614  2018-07-28 00:00:00
286   1625219    5536023764052314  2018-07-27 00:00:00
287   1671494    5536068139320738  2018-07-27 00:00:00
288   1537202    5536028011064176  2018-07-27 00:00:00
289   1266108    5536081517273945  2018-07-27 00:00:00
290   1181170    5536019227558273  2018-07-27 00:00:00
291   1964695    5536024050234162  2018-07-27 00:00:00
292   1596273    5536067575562256  2018-07-27 00:00:00
293   1185599    5536080003596764  2018-07-27 00:00:00
294   1270689    5536045973073303  2018-07-27 00:00:00
295   1710352    5536043991257465  2018-07-27 00:00:00
296   1101625    5536002595035008  2018-07-26 00:00:00
297   1934213    5536084511801649  2018-07-26 00:00:00
298   1326464    5536099484219600  2018-07-26 00:00:00
299   1832802    5536014537455806  2018-07-26 00:00:00
300   1789451    5536054629615595  2018-07-26 00:00:00
301   1132631    5536029089886348  2018-07-26 00:00:00
302   1412759    5536054092690943  2018-07-25 00:00:00
303   1677636    5536038121698688  2018-07-25 00:00:00
304   1020638    5536026390807760  2018-07-25 00:00:00
305   1990680    5536049113280534  2018-07-25 00:00:00
306   1088268    5536095033407398  2018-07-25 00:00:00
307   1990932    5536022653014792  2018-07-25 00:00:00
308   1159349    5536034930153034  2018-07-25 00:00:00
309   1936588    5536065583437376  2018-07-25 00:00:00
310   1214980    5536070330468063  2018-07-25 00:00:00
311   1268493    5536066466828362  2018-07-24 00:00:00
312   1470496    5536056269832609  2018-07-24 00:00:00
313   1380208    5536022686688631  2018-07-24 00:00:00
314   1665597    5536056948687319  2018-07-24 00:00:00
315   1670855    5536098011230079  2018-07-24 00:00:00
316   1049816    5536005222368755  2018-07-24 00:00:00
317   1941166    5536090136600701  2018-07-24 00:00:00
318   1148297    5536023275431599  2018-07-24 00:00:00
319   1342470    5536079012012656  2018-07-24 00:00:00
320   1281088    5536049805167862  2018-07-24 00:00:00
321   1700677    5536080790904863  2018-07-23 00:00:00
322   1522952    5536009851682091  2018-07-23 00:00:00
323   1204531    5536009284938943  2018-07-23 00:00:00
324   1624453    5536093774386114  2018-07-23 00:00:00
325   1315061    5536092855595791  2018-07-23 00:00:00
326   1445967    5536011223101520  2018-07-23 00:00:00
327   1868776    5536006975855969  2018-07-23 00:00:00
328   1365982    5536022698197144  2018-07-23 00:00:00
329   1517375    5536030332758851  2018-07-23 00:00:00
330   1443039    5536035743525492  2018-07-22 00:00:00
331   1534348    5536035132550774  2018-07-22 00:00:00
332   1261855    5536077382954762  2018-07-22 00:00:00
333   1811877    5536026995903269  2018-07-22 00:00:00
334   1212230    5536088353624834  2018-07-22 00:00:00
335   1923334    5536084932049108  2018-07-22 00:00:00
336   1071660    5536062645047983  2018-07-21 00:00:00
337   1719410    5536045998378127  2018-07-21 00:00:00
338   1978971    5536007810175999  2018-07-21 00:00:00
339   1639811    5536053919585058  2018-07-21 00:00:00
340   1225812    5536004371161067  2018-07-21 00:00:00
341   1277141    5536035195711162  2018-07-21 00:00:00
342   1963392    5536055905250183  2018-07-21 00:00:00
343   1283205    5536026177781811  2018-07-21 00:00:00
344   1750704    5536095598209372  2018-07-21 00:00:00
345   1880434    5536074094578419  2018-07-21 00:00:00
346   1373068    5536026599968572  2018-07-21 00:00:00
347   1844004    5536004319584469  2018-07-20 00:00:00
348   1225084    5536018419461208  2018-07-20 00:00:00
349   1760118    5536037228754098  2018-07-20 00:00:00
350   1499988    5536040863180308  2018-07-20 00:00:00
351   1981777    5536056573410466  2018-07-20 00:00:00
352   1500452    5536087841473207  2018-07-20 00:00:00
353   1924799    5536010962952322  2018-07-19 00:00:00
354   1034284    5536032961781054  2018-07-19 00:00:00
355   1429360    5536000876270644  2018-07-19 00:00:00
356   1187473    5536061467628829  2018-07-19 00:00:00
357   1272133    5536035470489513  2018-07-19 00:00:00
358   1492575    5536061944148180  2018-07-19 00:00:00
359   1860703    5536074900285037  2018-07-19 00:00:00
360   1043152    5536042629707384  2018-07-18 00:00:00
361   1737975    5536015155309498  2018-07-18 00:00:00

### Решение 2

In [13]:
sql = '''
          SELECT CLIENT_ID, CARD_ID
          FROM 
          
           ( SELECT CLIENT_ID,
                    CARD_ID,
                    OPEN_DATE,
                    MAX(OPEN_DATE),
                    CLOSE_DATE,
                    CARD_TYPE,
                    row_number() over (partition by CLIENT_ID order by OPEN_DATE) AS rn
             FROM CARD
             WHERE OPEN_DATE < '2018-09-01 00:00:00' AND CLOSE_DATE is null AND CARD_TYPE = '1')
             
           WHERE rn=1
           ORDER BY OPEN_DATE
      '''
select(sql)

   CLIENT_ID           CARD_ID
0  1683431    5536030318406556

## Задание 3: вывести количество активных клиентов на каждый месяц; долю клиентов, которые «оттекли» в каждом месяце. <a id="step3"></a>

### Для выполнения задания я создал импровизированную таблицу в excel, куда подставил даты REPORT_MONTH  и случайные значения client id (можно посмотреть ее [здесь](https://yadi.sk/d/BJaGxViJDKG98Q)) согласно примеру из тестового задания.Сейчас мы ее подгрузим, переведем в sql и выполним запрос

In [14]:
log = pd.read_excel('Log.xlsx')
log.head()

  REPORT_MONTH  CLIENT_ID
0 2018-02-23    7802
1 2017-08-29    8962
2 2017-06-17    4564
3 2017-06-09    1813
4 2017-05-31    6769

In [15]:
log = log.sort_values('REPORT_MONTH')
log.head()

      REPORT_MONTH  CLIENT_ID
4823  2017-01-01    8875
66503 2017-01-01    8833
72287 2017-01-01    3781
76717 2017-01-01    2726
81885 2017-01-01    8196

In [16]:
log.to_sql('log',
             conn,
             if_exists='replace', 
             index = False)

In [17]:
sql = '''select* 
         from log 
         limit 5 '''
select(sql)

          REPORT_MONTH  CLIENT_ID
0  2017-01-01 00:00:00  8875
1  2017-01-01 00:00:00  8833
2  2017-01-01 00:00:00  3781
3  2017-01-01 00:00:00  2726
4  2017-01-01 00:00:00  8196

### Здесь также у меня не получилось добавить условие в "3 месяца"...(

In [18]:
sql = ''' SELECT MONTH,
                 COUNT_USER ,
                 (100 - ((COUNT_USER* 1.0)/LAG)*100) AS CHURN_PERCENT
            FROM
                 (SELECT MONTH,
                         COUNT_USER,
                         LAG(COUNT_USER) OVER(ORDER BY MONTH) AS 'LAG'       
                  FROM       
                       (SELECT DATE(REPORT_MONTH) AS MONTH, 
                        COUNT(DISTINCT CLIENT_ID) as COUNT_USER
                        FROM log
                        GROUP BY strftime("%m-%Y", REPORT_MONTH)
                        ORDER BY REPORT_MONTH))
      '''
select(sql)

         MONTH  COUNT_USER  CHURN_PERCENT
0   2017-01-01  3338       NaN
1   2017-02-01  3107        6.920312
2   2017-03-01  3337       -7.402639
3   2017-04-01  3252        2.547198
4   2017-05-01  3290       -1.168512
5   2017-06-01  3261        0.881459
6   2017-07-01  3360       -3.035879
7   2017-08-01  3397       -1.101190
8   2017-09-01  3277        3.532529
9   2017-10-01  3363       -2.624352
10  2017-11-01  3178        5.501041
11  2017-12-01  3292       -3.587162
12  2018-01-01  3254        1.154313
13  2018-02-01  3123        4.025814
14  2018-03-01  3386       -8.421390
15  2018-04-01  3313        2.155936
16  2018-05-01  3375       -1.871416
17  2018-06-01  3257        3.496296
18  2018-07-01  3402       -4.451950
19  2018-08-01  3284        3.468548
20  2018-09-01  3304       -0.609013
21  2018-10-01  3341       -1.119855
22  2018-11-01  3274        2.005388
23  2018-12-01  3393       -3.634698
24  2019-01-01  139         95.903330

## Задание 4: Вывести 1000 клиентов, которые первыми набрали 1000 бонусных баллов за покупки в категории «Авиабилеты» и «Отели». <a id="step4"></a>

### Для выполнения задания я создал импровизированную таблицы в excel ( [bonus](https://yadi.sk/d/eeyEhAHtOzH9qw),[mcc_categories](https://yadi.sk/d/5oh2_oP28AlZUw)) согласно примеру из тестового задания.Сейчас мы ее подгрузим, переведем в sql и выполним запрос

In [19]:
bonus = pd.read_excel('BONUS.xlsx')
bonus.head()

   CLIENT_ID BONUS_DATE  BONUS_CNT   MCC
0  2739      2018-10-22  81         1112
1  2520      2018-06-01  27         1111
2  2853      2019-01-27  66         1112
3  1898      2019-01-29  11         1111
4  2009      2018-09-26  80         1116

In [20]:
bonus.to_sql('bonus',
             conn,
             if_exists='replace', 
             index = False)

In [21]:
sql = '''select* 
         from bonus 
         limit 5 '''
select(sql)

   CLIENT_ID           BONUS_DATE  BONUS_CNT   MCC
0  2739       2018-10-22 00:00:00  81         1112
1  2520       2018-06-01 00:00:00  27         1111
2  2853       2019-01-27 00:00:00  66         1112
3  1898       2019-01-29 00:00:00  11         1111
4  2009       2018-09-26 00:00:00  80         1116

In [22]:
mcc_categories = pd.read_excel('MCC_CATEGORIES.xlsx')
mcc_categories

    MCC MCC_CATEGORY
0  1111  Авиабилеты
1  1112  Музыка
2  1113  АЗС
3  1114  Отели
4  1115  Одежда
5  1116  Аптека
6  1117  Техника
7  1118  Дети
8  1119  Развлечения

In [23]:
mcc_categories.to_sql('mcc_categories',
             conn,
             if_exists='replace', 
             index = False)

In [24]:
sql = '''select* 
         from mcc_categories 
    '''
select(sql)

    MCC MCC_CATEGORY
0  1111  Авиабилеты
1  1112  Музыка
2  1113  АЗС
3  1114  Отели
4  1115  Одежда
5  1116  Аптека
6  1117  Техника
7  1118  Дети
8  1119  Развлечения

### Здесь все ок) 
### Кроме того, что мой импровизированный датасет не позволил мне найти клиентов с 1000 баллами, таких просто нет, поэтому я остановился на 500 баллах, и 1000 клиентов с 500 баллами тоже не набралось, но тем не менее этот запрос отработает, если поменять where NAR >= *** )

In [26]:
sql = ''' SELECT CLIENT,
                 DATE,
                 NAR
          FROM
            (SELECT CLIENT,
                    DATE,
                    BONUS,
                    NAR,
                    ROW_NUMBER () OVER (PARTITION BY CLIENT order by DATE ) AS ROW
             FROM
                 (SELECT CLIENT_ID AS CLIENT,
                         BONUS_DATE AS DATE,
                         BONUS_CNT AS BONUS,
                         SUM(BONUS_CNT) over (PARTITION BY CLIENT_ID 
                                          order by BONUS_DATE rows between unbounded preceding and current row) AS NAR
                  FROM bonus JOIN mcc_categories ON bonus.MCC = mcc_categories.MCC
                  WHERE MCC_CATEGORY IN ('Авиабилеты',
                                        'Отели')
                  ORDER BY CLIENT_ID)
                  WHERE NAR >= 500
                  ORDER BY DATE)
           WHERE ROW = 1
           LIMIT 1000
      '''
select(sql)

     CLIENT                 DATE  NAR
0    1191    2018-09-24 00:00:00  512
1    1093    2018-11-08 00:00:00  500
2    1481    2018-11-26 00:00:00  572
3    2395    2018-12-02 00:00:00  571
4    1562    2018-12-06 00:00:00  576
5    1915    2018-12-06 00:00:00  532
6    2495    2018-12-19 00:00:00  505
7    1162    2018-12-29 00:00:00  542
8    2366    2019-01-21 00:00:00  524
9    1642    2019-01-25 00:00:00  518
10   2454    2019-02-02 00:00:00  537
11   1928    2019-02-07 00:00:00  529
12   1869    2019-02-15 00:00:00  554
13   1268    2019-02-16 00:00:00  502
14   1171    2019-03-06 00:00:00  502
15   1402    2019-03-06 00:00:00  534
16   1262    2019-03-10 00:00:00  557
17   1901    2019-03-25 00:00:00  510
18   2180    2019-03-28 00:00:00  570
19   1735    2019-03-30 00:00:00  509
20   2302    2019-03-30 00:00:00  527
21   1485    2019-04-01 00:00:00  513
22   2751    2019-04-02 00:00:00  593
23   2469    2019-04-05 00:00:00  516
24   2321    2019-04-09 00:00:00  505
25   1357    2019-04-20 00:00:00  507
26   1756    2019-04-24 00:00:00  532
27   2243    2019-04-24 00:00:00  581
28   1100    2019-04-28 00:00:00  500
29   2463    2019-04-29 00:00:00  504
30   1307    2019-05-05 00:00:00  502
31   2753    2019-05-07 00:00:00  541
32   2287    2019-05-11 00:00:00  536
33   1185    2019-05-14 00:00:00  507
34   2523    2019-05-15 00:00:00  525
35   1817    2019-05-21 00:00:00  506
36   2577    2019-05-21 00:00:00  522
37   1518    2019-05-23 00:00:00  501
38   2749    2019-05-23 00:00:00  500
39   2819    2019-05-24 00:00:00  502
40   2653    2019-05-28 00:00:00  506
41   1296    2019-05-29 00:00:00  503
42   2687    2019-05-29 00:00:00  572
43   1548    2019-06-02 00:00:00  504
44   2390    2019-06-04 00:00:00  542
45   2701    2019-06-12 00:00:00  582
46   2107    2019-06-15 00:00:00  536
47   2412    2019-06-15 00:00:00  531
48   1237    2019-06-17 00:00:00  534
49   2863    2019-06-18 00:00:00  506
50   1038    2019-06-20 00:00:00  526
51   1892    2019-06-22 00:00:00  531
52   2658    2019-06-23 00:00:00  562
53   2966    2019-06-27 00:00:00  510
54   1765    2019-06-29 00:00:00  524
55   2996    2019-07-01 00:00:00  561
56   1342    2019-07-02 00:00:00  560
57   1662    2019-07-07 00:00:00  563
58   2019    2019-07-07 00:00:00  503
59   2732    2019-07-11 00:00:00  568
60   2481    2019-07-13 00:00:00  514
61   1526    2019-07-15 00:00:00  500
62   1849    2019-07-16 00:00:00  566
63   2525    2019-07-18 00:00:00  565
64   2227    2019-07-19 00:00:00  532
65   1391    2019-07-23 00:00:00  552
66   2152    2019-07-25 00:00:00  516
67   2981    2019-07-27 00:00:00  535
68   2532    2019-07-29 00:00:00  521
69   2417    2019-07-31 00:00:00  557
70   2965    2019-07-31 00:00:00  505
71   1474    2019-08-01 00:00:00  505
72   1840    2019-08-01 00:00:00  517
73   2825    2019-08-01 00:00:00  518
74   1496    2019-08-06 00:00:00  559
75   1832    2019-08-08 00:00:00  565
76   1529    2019-08-10 00:00:00  569
77   2254    2019-08-12 00:00:00  557
78   2775    2019-08-12 00:00:00  523
79   2846    2019-08-13 00:00:00  545
80   1105    2019-08-14 00:00:00  518
81   2442    2019-08-14 00:00:00  503
82   2613    2019-08-16 00:00:00  550
83   2852    2019-08-17 00:00:00  573
84   1692    2019-08-18 00:00:00  572
85   1741    2019-08-22 00:00:00  552
86   2479    2019-08-24 00:00:00  545
87   2244    2019-08-25 00:00:00  527
88   1536    2019-08-26 00:00:00  527
89   1101    2019-08-27 00:00:00  548
90   1443    2019-08-29 00:00:00  509
91   1883    2019-08-29 00:00:00  521
92   1344    2019-09-01 00:00:00  508
93   2831    2019-09-03 00:00:00  532
94   1129    2019-09-05 00:00:00  522
95   1942    2019-09-05 00:00:00  507
96   1012    2019-09-06 00:00:00  501
97   2768    2019-09-08 00:00:00  520
98   2790    2019-09-08 00:00:00  537
99   1705    2019-09-09 00:00:00  570
100  1992    2019-09-10 00:00:00  506
101  2307    2019-09-11 00:00:00  513
102  1864    2019-09-13 00:00:00  527
103  2186    2019-09-13 00:00:00  536
104  1206    2019-09-15 00:00:00  542
105  1782    2019-09-15 00:00:00  505
106  2477    2019-09-15 00:00:00  568
107  1745    2019-09-16 00:00:00  523
108  2251    2019-09-16 00:00:00  530
109  1254    2019-09-17 00:00:00  503
110  1769    2019-09-17 00:00:00  530
111  1221    2019-09-20 00:00:00  587
112  1349    2019-09-21 00:00:00  520
113  1593    2019-09-22 00:00:00  516
114  2201    2019-09-23 00:00:00  540
115  2823    2019-09-25 00:00:00  531
116  2894    2019-09-25 00:00:00  534
117  1693    2019-09-26 00:00:00  521
118  1030    2019-09-27 00:00:00  583
119  2647    2019-09-27 00:00:00  506
120  1888    2019-09-28 00:00:00  535
121  1227    2019-09-30 00:00:00  540
122  2640    2019-09-30 00:00:00  557
123  1361    2019-10-01 00:00:00  545
124  2997    2019-10-01 00:00:00  522
125  1627    2019-10-02 00:00:00  552
126  2348    2019-10-03 00:00:00  561
127  1640    2019-10-04 00:00:00  507
128  2073    2019-10-04 00:00:00  533
129  2113    2019-10-05 00:00:00  504
130  1426    2019-10-11 00:00:00  502
131  2279    2019-10-12 00:00:00  530
132  1608    2019-10-13 00:00:00  516
133  1764    2019-10-15 00:00:00  551
134  1768    2019-10-15 00:00:00  503
135  2399    2019-10-15 00:00:00  509
136  1134    2019-10-16 00:00:00  562
137  1997    2019-10-16 00:00:00  567
138  2497    2019-10-16 00:00:00  521
139  2300    2019-10-18 00:00:00  541
140  2119    2019-10-19 00:00:00  516
141  2204    2019-10-19 00:00:00  513
142  1750    2019-10-21 00:00:00  527
143  2400    2019-10-21 00:00:00  554
144  2803    2019-10-21 00:00:00  504
145  1265    2019-10-22 00:00:00  552
146  2661    2019-10-22 00:00:00  505
147  2720    2019-10-23 00:00:00  527
148  2008    2019-10-25 00:00:00  540
149  2202    2019-10-25 00:00:00  553
150  1433    2019-10-26 00:00:00  545
151  2693    2019-10-26 00:00:00  514
152  2574    2019-10-27 00:00:00  510
153  2167    2019-10-28 00:00:00  519
154  2767    2019-10-30 00:00:00  535
155  1138    2019-10-31 00:00:00  516
156  2802    2019-11-01 00:00:00  543
157  2915    2019-11-01 00:00:00  545
158  1723    2019-11-03 00:00:00  513
159  2370    2019-11-03 00:00:00  527
160  2261    2019-11-04 00:00:00  558
161  1004    2019-11-05 00:00:00  527
162  2436    2019-11-06 00:00:00  513
163  2025    2019-11-08 00:00:00  532
164  1067    2019-11-09 00:00:00  524
165  1366    2019-11-09 00:00:00  533
166  1436    2019-11-09 00:00:00  556
167  1487    2019-11-10 00:00:00  536
168  2824    2019-11-12 00:00:00  524
169  1126    2019-11-13 00:00:00  541
170  1673    2019-11-13 00:00:00  501
171  2006    2019-11-14 00:00:00  516
172  2729    2019-11-15 00:00:00  503
173  2439    2019-11-16 00:00:00  518
174  1537    2019-11-19 00:00:00  500
175  1774    2019-11-19 00:00:00  562
176  2153    2019-11-20 00:00:00  503
177  2104    2019-11-21 00:00:00  542
178  1232    2019-11-22 00:00:00  531
179  2267    2019-11-25 00:00:00  555
180  2173    2019-11-28 00:00:00  504
181  1247    2019-12-01 00:00:00  546
182  1573    2019-12-01 00:00:00  502
183  2393    2019-12-01 00:00:00  546
184  1177    2019-12-03 00:00:00  565
185  2464    2019-12-03 00:00:00  547
186  1980    2019-12-04 00:00:00  515
187  1001    2019-12-05 00:00:00  534
188  2388    2019-12-07 00:00:00  555
189  2662    2019-12-07 00:00:00  535
190  2990    2019-12-08 00:00:00  503
191  2795    2019-12-09 00:00:00  541
192  1017    2019-12-10 00:00:00  505
193  1442    2019-12-10 00:00:00  500
194  2604    2019-12-12 00:00:00  507
195  1412    2019-12-14 00:00:00  518
196  1851    2019-12-14 00:00:00  531
197  1102    2019-12-16 00:00:00  521
198  2082    2019-12-20 00:00:00  505
199  2427    2019-12-21 00:00:00  519
200  2288    2019-12-22 00:00:00  586
201  2677    2019-12-22 00:00:00  528
202  2314    2019-12-23 00:00:00  540
203  2688    2019-12-23 00:00:00  511
204  1978    2019-12-24 00:00:00  523
205  2544    2019-12-24 00:00:00  511
206  1028    2019-12-25 00:00:00  534
207  1400    2019-12-26 00:00:00  516
208  2035    2019-12-26 00:00:00  549
209  2340    2019-12-26 00:00:00  524
210  1872    2019-12-27 00:00:00  597
211  2056    2019-12-28 00:00:00  500
212  2926    2019-12-28 00:00:00  520
213  2762    2019-12-29 00:00:00  501
214  2230    2020-01-01 00:00:00  512
215  2451    2020-01-01 00:00:00  520
216  2972    2020-01-01 00:00:00  535